<?php session_start(); ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sneak Me</title>
</head>
<body>
    <header> <?php require './views/header.phtml' ?></header>
    <div>
        <div>        
            <main>
                <?php $router = new router() ?>
            </main>
        </div>
    </div>
</body>
</html>